#Время в часах сколько надо отыграть игроку для снятия ограничения
required-playtime-hours: 48

blocked-items:
  - DIAMOND
  - DIAMOND_BLOCK
  - NETHERITE_INGOT
  - NETHERITE_SCRAP
  - TNT
  - ELYTRA
  - SHULKER_BOX

message: "<red>Вы не можете взять этот предмет! Наиграйте больше времени.</red>"

#Знак % заменяется на время в игре
time-message: "<yellow>Осталось наиграть: % ч.<yellow>"

#Отключает отображение времени игроку который пытался что то подобрать из блек листа
show-remaining-time: true

#Задежка в тиках против спама сообщениями в чате (20тик = 1сек)
delay-message: 100
